import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {},
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react", "nextjs"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "node_modules/**",
      "public/**",
      "*.config.js",
      "*.config.mjs",
      "*.config.ts",
      "storybook-static/**",
    ],
    rules: {
      "nextjs/no-html-link-for-pages": "error",
      "nextjs/no-sync-scripts": "error",
      "nextjs/inline-script-id": "error",
      "nextjs/no-assign-module-variable": "error",
      "nextjs/no-document-import-in-page": "error",
      "nextjs/no-duplicate-head": "error",
      "nextjs/no-head-import-in-document": "error",
      "nextjs/no-script-component-in-head": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
        rules: {
          "react/display-name": "error",
          "react/jsx-key": "error",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-target-blank": "off",
          "react/jsx-no-undef": "error",
          "react/no-children-prop": "error",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-find-dom-node": "error",
          "react/no-is-mounted": "error",
          "react/no-render-return-value": "error",
          "react/no-string-refs": "error",
          "react/no-unescaped-entities": "error",
          "react/no-unknown-property": "off",
          "react/no-unsafe": "off",
          "react/react-in-jsx-scope": "off",
          "react/require-render-return": "error",
          "import/no-anonymous-default-export": "warn",
          "jsx-a11y/alt-text": [
            "warn",
            {
              elements: ["img"],
              img: ["Image"],
            },
          ],
          "jsx-a11y/aria-props": "warn",
          "jsx-a11y/aria-proptypes": "warn",
          "jsx-a11y/aria-unsupported-elements": "warn",
          "jsx-a11y/role-has-required-aria-props": "warn",
          "jsx-a11y/role-supports-aria-props": "warn",
          "nextjs/google-font-display": "warn",
          "nextjs/google-font-preconnect": "warn",
          "nextjs/next-script-for-ga": "warn",
          "nextjs/no-async-client-component": "warn",
          "nextjs/no-before-interactive-script-outside-document": "warn",
          "nextjs/no-css-tags": "warn",
          "nextjs/no-head-element": "warn",
          "nextjs/no-html-link-for-pages": "warn",
          "nextjs/no-img-element": "warn",
          "nextjs/no-page-custom-font": "warn",
          "nextjs/no-styled-jsx-in-document": "warn",
          "nextjs/no-sync-scripts": "warn",
          "nextjs/no-title-in-document-head": "warn",
          "nextjs/no-typos": "warn",
          "nextjs/no-unwanted-polyfillio": "warn",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
        },
        plugins: ["import", "jsx-a11y"],
        env: {
          node: true,
          browser: true,
        },
      },
      {
        files: ["**/*.ts", "**/*.tsx"],
        rules: {
          "react/jsx-no-useless-fragment": "warn",
          "react/self-closing-comp": "error",
          "react/jsx-curly-brace-presence": [
            "error",
            {
              props: "never",
              children: "never",
            },
          ],
          "no-console": "off",
          "no-debugger": "error",
          "no-duplicate-imports": "off",
          "no-unused-expressions": "error",
          "prefer-const": "error",
          "no-var": "error",
          eqeqeq: [
            "error",
            "always",
            {
              null: "ignore",
            },
          ],
          curly: ["error", "all"],
          "jsx-a11y/alt-text": "error",
          "jsx-a11y/anchor-is-valid": "error",
          "jsx-a11y/aria-props": "error",
          "jsx-a11y/aria-role": "error",
          "jsx-a11y/click-events-have-key-events": "off",
          "jsx-a11y/no-static-element-interactions": "off",
          "jsx-a11y/label-has-associated-control": "off",
          "jsx-a11y/no-noninteractive-element-interactions": "off",
          "react/jsx-pascal-case": "error",
          "react/no-unescaped-entities": "off",
          "no-unused-vars": [
            "error",
            {
              argsIgnorePattern: "^_",
              varsIgnorePattern: "^_",
              caughtErrorsIgnorePattern: "^_",
            },
          ],
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
          "typescript/no-explicit-any": "off",
          "typescript/explicit-module-boundary-types": "off",
          "typescript/consistent-type-imports": [
            "error",
            {
              prefer: "type-imports",
              disallowTypeAnnotations: false,
            },
          ],
        },
        plugins: ["jsx-a11y"],
      },
      {
        files: [
          "app/**/*.ts",
          "app/**/*.tsx",
          "lib/**/*.ts",
          "lib/**/*.tsx",
          "components/**/*.ts",
          "components/**/*.tsx",
          "hooks/**/*.ts",
          "hooks/**/*.tsx",
        ],
        rules: {
          "no-console": "error",
        },
      },
      {
        files: [
          "lib/logger.ts",
          "lib/client-logger.ts",
          "**/*.test.ts",
          "**/*.test.tsx",
          "**/*.spec.ts",
          "**/*.spec.tsx",
          "tests/**",
          "scripts/**",
        ],
        rules: {
          "no-console": "off",
        },
      },
    ],
    options: {
      typeAware: false,
      typeCheck: false,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
  },
});
